apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.name" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 33
{{- if .Values.passbolt.persistence.enabled }}
      initContainers:
      # copy default img folder's files to a volume
      - name: copy-default-img
        image: {{ .Values.passbolt.image }}:{{ .Values.passbolt.imageTag }}
        command: ["sh", "-c", "mkdir -p /data/img && mkdir -p /data/gpg && cp -r /var/www/passbolt/webroot/img/* /data/img/"]
        volumeMounts:
        - name: data
          mountPath: /data
{{- end }}
      containers:
      - image: {{ .Values.passbolt.image }}:{{ .Values.passbolt.imageTag }}
        imagePullPolicy: {{ .Values.passbolt.imagePullPolicy }}
        name: {{ template "app.name" . }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "chown -R 33:33 /var/www/passbolt"]
        env:
        - name: DATASOURCES_DEFAULT_HOST
          value: {{ .Release.Name }}-mysql
        - name: DATASOURCES_DEFAULT_USERNAME
          value: {{ .Values.mysql.mysqlUser }}
        - name: DATASOURCES_DEFAULT_DATABASE
          value: passbolt
        - name: APP_FULL_BASE_URL
          value: https://{{ .Values.passbolt.ingress.host }}
        - name: DATASOURCES_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql
              key: mysql-password
        ports:
        - containerPort: {{ .Values.passbolt.ports.http }}
          name: http
          protocol: TCP
        - containerPort: {{ .Values.passbolt.ports.https }}
          name: https
          protocol: TCP
{{- if .Values.passbolt.persistence.enabled }}
        volumeMounts:
        # data volume
        - mountPath: /var/www/passbolt/webroot/img
          name: data
          subPath: img
        - mountPath: /var/www/passbolt/config/gpg
          name: data
          subPath: gpg
        - mountPath: /etc/ssl/certs/certificate.crt
          name: data
          subPath: certificate.crt
        - mountPath: /etc/ssl/certs/certificate.key
          name: data
          subPath: certificate.key
{{- end }}
        resources:
{{ toYaml .Values.passbolt.resources | indent 10 }}
{{- if .Values.passbolt.persistence.enabled }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-data
{{- end -}}
