apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: mysql
    port: {{ .Values.mysql.ports.mysql }}
    protocol: TCP
    targetPort: {{ .Values.mysql.ports.mysql }}
  selector:
    app: mysql
    release: {{ .Release.Name }}
