apiVersion: v1
kind: Secret
metadata:
  name: mysql
  labels:
    app: mysql
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  rootPassword: {{ .Values.mysql.rootPassword | b64enc }}
  userPassword: {{ .Values.mysql.userPassword | b64enc }}
