apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (.Files.Glob "config/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-probes
  labels:
    app: mysql
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (.Files.Glob "probes/*").AsConfig | indent 2 }}
