apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: {{ template "app.name" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "app.name" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 33
      initContainers:
      # copy default img folder's files to a volume
      - name: copy-default-img
        image: {{ .Values.passbolt.image }}:{{ .Values.passbolt.imageTag }}
        command: ["sh", "-c", "mkdir -p /data/img && mkdir -p /data/gpg && cp -r /var/www/passbolt/webroot/img/* /data/img/"]
        volumeMounts:
        - name: data
          mountPath: /data
      containers:
      - image: {{ .Values.passbolt.image }}:{{ .Values.passbolt.imageTag }}
        imagePullPolicy: {{ .Values.passbolt.imagePullPolicy }}
        name: {{ template "app.name" . }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "chown -R 33:33 /var/www/passbolt"]
        env:
        - name: DATASOURCES_DEFAULT_HOST
          value: mysql
        - name: DATASOURCES_DEFAULT_USERNAME
          value: passbolt
        - name: DATASOURCES_DEFAULT_DATABASE
          value: passbolt
        - name: APP_FULL_BASE_URL
          value: https://{{ .Values.passbolt.ingress.host }}
        - name: DATASOURCES_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: userPassword
        ports:
        - containerPort: {{ .Values.passbolt.ports.http }}
          name: http
          protocol: TCP
        - containerPort: {{ .Values.passbolt.ports.https }}
          name: https
          protocol: TCP
        volumeMounts:
        # data volume
        - mountPath: /var/www/passbolt/webroot/img
          name: data
          subPath: img
        - mountPath: /var/www/passbolt/config/gpg
          name: data
          subPath: gpg
        - mountPath: /etc/ssl/certs/certificate.crt
          name: data
          subPath: certificate.crt
        - mountPath: /etc/ssl/certs/certificate.key
          name: data
          subPath: certificate.key
        resources:
{{ toYaml .Values.passbolt.resources | indent 10 }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        {{- range .Values.passbolt.persistence.accessModes }}
        - {{ . | quote }}
        {{- end }}
      resources:
        requests:
          storage: {{ .Values.passbolt.persistence.size | quote }}
      storageClassName: {{ .Values.passbolt.persistence.storageClassName }}
