apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: http
    port: {{ .Values.passbolt.ports.http }}
    protocol: TCP
    targetPort: {{ .Values.passbolt.ports.http }}
  - name: https
    port: {{ .Values.passbolt.ports.https }}
    protocol: TCP
    targetPort: {{ .Values.passbolt.ports.https }}
  type: ClusterIP
  selector:
    app: {{ template "app.name" . }}
    release: {{ .Release.Name }}
