{{- if and .Values.passbolt.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-data
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.passbolt.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.passbolt.persistence.size | quote }}
{{- if .Values.passbolt.persistence.storageClass }}
{{- if (eq "-" .Values.passbolt.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.passbolt.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
